swagger: '2.0'
info:
  title: JSONPlaceholder Job Role API
  description: Returns user data including company (job role) by employee ID
  version: '1.0'
host: jsonplaceholder.typicode.com
schemes:
  - https
basePath: /
paths:
  /users/{employeeId}:
    get:
      summary: Get user by employee ID
      parameters:
        - name: employeeId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Full user object response (including company)
          schema:
            type: object
            properties:
              company:
                type: object
                properties:
                  name:
                    type: string
        default:
          description: Error response
