swagger: '2.0'
info:
  title: Proxy API for Company Name
  description: Returns only job role (company name) by employee ID
  version: '1.0'
host: your-proxy-host.com
schemes:
  - https
basePath: /
paths:
  /users/{employeeId}:
    get:
      summary: Get job role by employee ID
      parameters:
        - name: employeeId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Response containing job role string
          schema:
            type: object
            properties:
              jobRole:
                type: string
        default:
          description: Error response
